Repository DSGT-DLP/Deep-Learning-Playground, pull requests merged in 2023-06, with the labels that each got.

#793 Remove Pretrained Backend Code
  backend/dl/pretrained.py
  tests/test_imports.py
  tests/test_pretrained_train.py
Labels: code cleanup

#797 Typo Github Issue Form
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: code cleanup

#806 prettify auto-gen issue comment
  .github/workflows/issue-form-submission.yml
Labels: scalability

#808 markdown cleanup
  .github/workflows/issue-form-submission.yml
Labels: scalability

#819 ttl dataset file
  frontend/src/features/Train/components/DatasetStepLayout.tsx
  tmux-script.sh
Labels: enhancement
